// One-off seed: wipes existing data and inserts a single test user + 3 items.
// Run with: pnpm dlx tsx scripts/seed.ts

import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "../generated/prisma/client";

async function main() {
  const prisma = new PrismaClient({
    adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL! }),
  });

  // Cascading delete: removing User cascades to Item, Tag, ItemTag
  // (because of `onDelete: Cascade` in schema.prisma).
  await prisma.user.deleteMany();

  // Create user; `id` and `createdAt` auto-generated by @default(cuid())/now().
  const user = await prisma.user.create({
    data: {
      email: "zgnaksoy@gmail.com",
      name: "Ozgun",
    },
  });
  console.log("Created user:", user);

  // Create 3 items, all owned by this user.
  // `type` and `status` are enums — TS will reject invalid values at compile time.
  const items = await prisma.item.createManyAndReturn({
    data: [
      {
        userId: user.id,
        title: "Dune",
        type: "BOOK",
        status: "DONE",
        rating: 5,
        notes: "Sandworms.",
      },
      {
        userId: user.id,
        title: "Severance",
        type: "SHOW",
        status: "IN_PROGRESS",
      },
      {
        userId: user.id,
        title: "The Expanse",
        type: "SHOW",
        status: "WANT",
      },
    ],
  });
  console.log(`Created ${items.length} items.`);

  await prisma.$disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
